### ISSUE TITLE
Random Error Message (Not Critical)

### ISSUE THREAD

**Issue by Nikogenia** [BenCodez/GraveStonesPlus#19]
First of all, a fantastic plugin! You did a really good job here! But I get the same error message regularly in the console. Even tho I didn't notice any problems, I think it could be useful to report it. So here is the error:

```
[22:46:25 WARN]: Exception in thread "Timer-2" java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.removeMetadata(String, org.bukkit.plugin.Plugin)" because "entity" is null
[22:46:25 WARN]: 	at GraveStonesPlus.jar//com.bencodez.gravestonesplus.advancedcore.api.misc.MiscUtils.setEntityMeta(MiscUtils.java:458)
[22:46:25 WARN]: 	at GraveStonesPlus.jar//com.bencodez.gravestonesplus.graves.Grave.checkGlowing(Grave.java:306)
[22:46:25 WARN]: 	at GraveStonesPlus.jar//com.bencodez.gravestonesplus.GraveStonesPlus$1.run(GraveStonesPlus.java:182)
[22:46:25 WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[22:46:25 WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
```

Maybe it could be useful for you! Greetings Nikogenia

**Comment by BenCodez** [comment]
Are you on the latest version?

**Comment by Nikogenia** [comment]
Yes, I downloaded it an hour ago.

**Comment by BenCodez** [comment]
It's safe to ignore, shouldn't case any problems, I'll see what I can do about it though
