### ISSUE TITLE
Multiple errors.

### ISSUE THREAD

**Issue by csBlackWolf** [BenCodez/GraveStonesPlus#4]
I running this plugin on a 1.19 minecrafts server and see multiple error messages in the logfile.

The first was, as a player died in the nether:
```
[06:51:23 WARN]: Exception in thread "Timer-9" java.lang.IllegalArgumentException: Cannot measure distance between Sushi Cafe and Sushi Cafe_nether
[06:51:23 WARN]:        at org.bukkit.Location.distanceSquared(Location.java:510)
[06:51:23 WARN]:        at org.bukkit.Location.distance(Location.java:493)
[06:51:23 WARN]:        at GraveStonesPlus.jar//com.bencodez.gravestonesplus.graves.Grave.checkGlowing(Grave.java:257)
[06:51:23 WARN]:        at GraveStonesPlus.jar//com.bencodez.gravestonesplus.GraveStonesPlus$1.run(GraveStonesPlus.java:146)
[06:51:23 WARN]:        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[06:51:23 WARN]:        at java.base/java.util.TimerThread.run(Timer.java:516)
```
![grafik](https://user-images.githubusercontent.com/30509936/178653738-f3d64937-29cd-4de0-9ab1-e267ff31b417.png)
 
 As the player trys to get his stuff back, this error occured:
```
 [06:56:09 ERROR]: Could not pass event BlockBreakEvent to GraveStonesPlus v1.3.2
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getAmount()" because "item" is null
        at com.bencodez.gravestonesplus.advancedcore.api.user.AdvancedCoreUser.giveItem(AdvancedCoreUser.java:495) ~[GraveStonesPlus.jar:?]
        at com.bencodez.gravestonesplus.graves.Grave.claim(Grave.java:401) ~[GraveStonesPlus.jar:?]
        at com.bencodez.gravestonesplus.listeners.PlayerBreakBlock.onBlockBreak(PlayerBreakBlock.java:98) ~[GraveStonesPlus.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor71.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-58]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:373) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:332) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:296) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1802) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-58]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-58]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
![grafik](https://user-images.githubusercontent.com/30509936/178655365-eb78a694-f7d1-4702-8557-3d12ec8f97fe.png)

Now we have a user who lost all his stuff and i can't do anything about it at the moment.

 running Paper version git-Paper-58 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e294802)

**Comment by BenCodez** [comment]
https://bencodez.com/job/GraveStonesPlus/ should fix the errors

**Comment by csBlackWolf** [comment]
The errors seems to be fixed now. ❤️ 

But i can't brake the graves from other users. I have set the permission "GraveStonesPlus.BreakOtherGraves" for this.
There is no error in the log when i try to break it. It just says "Not your grave!". 
---
It would be also nice, if it would be possible, that admins can just view the inventory what is saved in a grave. 😄

**Comment by BenCodez** [comment]
> The errors seems to be fixed now. heart
> 
> But i can't brake the graves from other users. I have set the permission "GraveStonesPlus.BreakOtherGraves" for this. There is no error in the log when i try to break it. It just says "Not your grave!".
> 
> It would be also nice, if it would be possible, that admins can just view the inventory what is saved in a grave. smile

did you reload the plugin/try a restart. I think there is a config option as well. You can break the grave within the GUI of all graves

**Comment by csBlackWolf** [comment]
The settings at the config seems ok.
![grafik](https://user-images.githubusercontent.com/30509936/179369400-c90aca0d-6194-4c44-8803-326658956091.png)
The server does a daily auto-restart. I can test it again tomorrow, after the restart is done.

**Comment by BenCodez** [comment]
try /gravestonesplus reload?

**Comment by csBlackWolf** [comment]
I can't break the grave by hand, but via the GUI it works without any problems. Thanks for this plugin and your effort. 👍
