### ISSUE TITLE
Graves are simply deleted

### ISSUE THREAD

**Issue by Joko-1** [BenCodez/GraveStonesPlus#47]
Issue:
This is the second time that graves have been deleted, and you only get the player's head when you destroy them.

Server:
Aternos:
Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
GraveStonesPlus 1.7

Log:
```
[15:06:05] [ServerMain/INFO]: Loaded 7 recipes
[15:06:06] [Server thread/INFO]: Starting minecraft server version 1.19.2
[15:06:06] [Server thread/INFO]: Loading properties
[15:06:06] [Server thread/INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
[15:06:07] [Server thread/INFO]: Server Ping Player Sample Count: 12
[15:06:07] [Server thread/INFO]: Using 4 threads for Netty based IO
[15:06:07] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[15:06:07] [Server thread/INFO]: Default game type: SURVIVAL
[15:06:07] [Server thread/INFO]: Generating keypair
[15:06:07] [Server thread/INFO]: Starting Minecraft server on *:48134
[15:06:07] [Server thread/INFO]: Using epoll channel type
[15:06:07] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[15:06:07] [Server thread/INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[15:06:08] [Server thread/INFO]: [GraveStonesPlus] Loading 1 libraries... please wait
[15:06:08] [Server thread/INFO]: Downloading https://repo.maven.apache.org/maven2/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.pom
[15:06:08] [Server thread/INFO]: Downloading https://repo.maven.apache.org/maven2/org/ow2/asm/asm/7.3.1/asm-7.3.1.pom
[15:06:08] [Server thread/INFO]: Downloading https://repo.maven.apache.org/maven2/org/ow2/ow2/1.5/ow2-1.5.pom
[15:06:08] [Server thread/INFO]: Downloading https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/7.3.1/asm-commons-7.3.1.pom
[15:06:08] [Server thread/INFO]: Downloading https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/7.3.1/asm-tree-7.3.1.pom
[15:06:08] [Server thread/INFO]: Downloading https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/7.3.1/asm-analysis-7.3.1.pom
[15:06:08] [Server thread/INFO]: Downloading https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/7.3.1/asm-util-7.3.1.pom
[15:06:08] [BasicRepositoryConnector-repo.maven.apache.org-0-0/INFO]: Downloading https://repo.maven.apache.org/maven2/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
[15:06:08] [BasicRepositoryConnector-repo.maven.apache.org-0-3/INFO]: Downloading https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/7.3.1/asm-analysis-7.3.1.jar
[15:06:08] [BasicRepositoryConnector-repo.maven.apache.org-0-1/INFO]: Downloading https://repo.maven.apache.org/maven2/org/ow2/asm/asm/7.3.1/asm-7.3.1.jar
[15:06:08] [BasicRepositoryConnector-repo.maven.apache.org-0-4/INFO]: Downloading https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/7.3.1/asm-tree-7.3.1.jar
[15:06:08] [BasicRepositoryConnector-repo.maven.apache.org-0-2/INFO]: Downloading https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/7.3.1/asm-commons-7.3.1.jar
[15:06:08] [BasicRepositoryConnector-repo.maven.apache.org-0-3/INFO]: Downloading https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/7.3.1/asm-util-7.3.1.jar
[15:06:09] [Server thread/INFO]: [GraveStonesPlus] Loaded library /server/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
[15:06:09] [Server thread/INFO]: [GraveStonesPlus] Loaded library /server/libraries/org/ow2/asm/asm/7.3.1/asm-7.3.1.jar
[15:06:09] [Server thread/INFO]: [GraveStonesPlus] Loaded library /server/libraries/org/ow2/asm/asm-commons/7.3.1/asm-commons-7.3.1.jar
[15:06:09] [Server thread/INFO]: [GraveStonesPlus] Loaded library /server/libraries/org/ow2/asm/asm-analysis/7.3.1/asm-analysis-7.3.1.jar
[15:06:09] [Server thread/INFO]: [GraveStonesPlus] Loaded library /server/libraries/org/ow2/asm/asm-tree/7.3.1/asm-tree-7.3.1.jar
[15:06:09] [Server thread/INFO]: [GraveStonesPlus] Loaded library /server/libraries/org/ow2/asm/asm-util/7.3.1/asm-util-7.3.1.jar
[15:06:09] [Server thread/INFO]: [GraveStonesPlus] Loading GraveStonesPlus v1.7
[15:06:09] [Server thread/INFO]: [XPBorder] Loading XPBorder v1.1.4
[15:06:09] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:06:09] [Server thread/INFO]: Preparing level "world"
[15:06:10] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:06:10] [Server thread/INFO]: Time elapsed: 199 ms
[15:06:10] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[15:06:10] [Server thread/INFO]: Time elapsed: 32 ms
[15:06:10] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[15:06:10] [Server thread/INFO]: Time elapsed: 96 ms
[15:06:10] [Server thread/INFO]: [GraveStonesPlus] Enabling GraveStonesPlus v1.7
[15:06:11] [Server thread/INFO]: [XPBorder] Enabling XPBorder v1.1.4
[15:06:11] [Server thread/INFO]: [XPBorder] Found version: v1_19_R1
[15:06:11] [Server thread/INFO]: [XPBorder] Checking for updates
[15:06:11] [Server thread/INFO]: [XPBorder] No data was migrated!
[15:06:11] [Server thread/INFO]: [XPBorder] Loading 9 settings...
[15:06:12] [Server thread/INFO]: Starting GS4 status listener
[15:06:12] [Server thread/INFO]: Thread Query Listener started
[15:06:12] [Query Listener #1/INFO]: Query running on 0.0.0.0:9898
[15:06:12] [Server thread/INFO]: JMX monitoring enabled
[15:06:12] [Server thread/INFO]: Running delayed init tasks
[15:06:12] [Craft Scheduler Thread - 4 - GraveStonesPlus/INFO]: [GraveStonesPlus] GraveStonesPlus is up to date! Version: 1.7
[15:06:12] [Server thread/WARN]: [GraveStonesPlus] Task #6 for GraveStonesPlus v1.7 generated an exception
java.lang.NoSuchFieldError: ITEM_DISPLAY
	at com.bencodez.gravestonesplus.graves.Grave.removeHologramsAround(Grave.java:212) ~[GraveStonesPlus.jar:?]
	at com.bencodez.gravestonesplus.GraveStonesPlus$1.run(GraveStonesPlus.java:115) ~[GraveStonesPlus.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1114) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[15:06:12] [Server thread/WARN]: [GraveStonesPlus] Task #7 for GraveStonesPlus v1.7 generated an exception
java.lang.NoSuchFieldError: ITEM_DISPLAY
	at com.bencodez.gravestonesplus.graves.GraveDisplayEntityHandle.getItemDisplay(GraveDisplayEntityHandle.java:40) ~[GraveStonesPlus.jar:?]
	at com.bencodez.gravestonesplus.graves.Grave.checkBlockDisplay(Grave.java:706) ~[GraveStonesPlus.jar:?]
	at com.bencodez.gravestonesplus.GraveStonesPlus$2.run(GraveStonesPlus.java:156) ~[GraveStonesPlus.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1114) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[15:06:12] [Server thread/INFO]: Done (5.889s)! For help, type "help"
[15:06:12] [Server thread/INFO]: Timings Reset
[15:06:19] [Server thread/WARN]: [GraveStonesPlus] Failed to hook into vault economy
[15:06:19] [Server thread/WARN]: [GraveStonesPlus] Failed to hook into vault permissions
[15:06:34] [User Authenticator #0/INFO]: UUID of player User is ID
[15:06:35] [Server thread/INFO]: User joined the game
[15:06:35] [Server thread/INFO]: User[IP adress] logged in with entity id 844 at ([world]547.5, 67.0, -254.5)
[15:07:11] [pool-14-thread-1/INFO]: [GraveStonesPlus] Detected day changed, processing...
[15:07:11] [pool-14-thread-1/INFO]: [GraveStonesPlus] Time change event: DAY, Fake: false
[15:07:11] [pool-14-thread-1/INFO]: [GraveStonesPlus] Finished processing day changes
```
*Username, UUID, and IP censored

**Comment by BenCodez** [comment]
Send your config and what version of minecraft your on

**Comment by Joko-1** [comment]
Thanks for your response!
This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
GraveStonesPlus 1.7
config files:
[Config.zip](https://github.com/user-attachments/files/17165826/Config.zip)

The first time this happened, the Graves.yml were complete empty, the 2. time some graves got deleted

**Comment by BenCodez** [comment]
https://bencodez.com/job/GraveStonesPlus/

Issue is with your minecraft version, newer version wouldn't have the issue, see if that helps

**Comment by BenCodez** [comment]
yes

**Comment by Joko-1** [comment]
WOW thanks!
